name: Update Publications from ORCID

on:
  schedule:
    - cron: '0 0 * * 0'  # weekly on Sunday
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-publications:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ORCID fetch script
        run: python scripts/fetch_orcid_publications.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add content/publication/
          git commit -m "Update publications from ORCID" || echo "No changes to commit"
          git push